// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxjjioprpltpxtxgrhet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4amppb3BycGx0cHh0eGdyaGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MjgwNjAsImV4cCI6MjA1NDMwNDA2MH0.1Oj3WthuJZRFQDENIMPD6wOxZMEktrHR6qir5rRLt1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);